# Resolve react_native_pods.rb
require File.expand_path('../../../node_modules/react-native/scripts/react_native_pods', __dir__)

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'RNPrebuild' do
  use_frameworks! :linkage => :static
  use_react_native!(path: '../../../node_modules/react-native')
end

post_install do |installer|
  react_native_post_install(
    installer,
    '../../../node_modules/react-native',
    :mac_catalyst_enabled => false,
  )
end
