require_relative './node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'RNPrebuild' do
  use_frameworks! :linkage => :static
  use_react_native!(path: './node_modules/react-native')
end
