[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib", "../../node_modules"]

remappings = [
    "@openzeppelin/contracts/=../../node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/",
    "interfaces/=src/interfaces/",
    "errors/=src/errors/"
]

ignored_error_codes = [2424]

[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }